sila/blueprints/projects.py
"""Project related endpoints.
"""
import os
import random
from shutil import move

from flask import abort, Blueprint, render_template, request, flash, redirect, url_for, send_from_directory

from sila.models import db, Project, Phase, PhaseTypeEnum
from sila.forms import ProjectForm, PhaseForm

bp = Blueprint('projects', __name__, url_prefix='/projects')

MODERATE_SAMPLE_SIZE = 5

@bp.route('/', methods=['GET'])
def projects():
    active_projects = Project.query.all()
    data = {
        'page_title': 'Projects',
        'active_projects': active_projects
    }
    return render_template('projects.html', **data)

@bp.route('/new/', methods=['GET', 'POST'])
def project_new():
    form = ProjectForm(request.form)

    if request.method == 'POST' and form.validate():
        project = Project(name=form.name.data, description=form.description.data)
        db.session.add(project)
        db.session.commit()
        flash(f'New project <strong>{project.name}</strong> is created.', 'success')
        return redirect(url_for('projects.projects'))

    else:
        data = {
            'page_title': 'Create Project',
            'form': form
        }
        return render_template('project-form.html', **data)

@bp.route('/<int:project_id>', methods=['GET', 'POST'])
def project_edit(project_id):

    def _render_with_form(form):
        data = {
            'page_title': 'Edit Project',
            'project': project,
            'form': form,
            'new_phase_form': new_phase_form,
        }
        return render_template('project-form.html', **data)

    project = Project.query.get(project_id)
    new_phase_form = PhaseForm()

    if request.method == 'POST':
        form = ProjectForm(request.form)
        if 'delete' in request.form:
            Project.query.filter_by(id=request.form['id']).delete()
            flash(f'Project <strong>{project.name}</strong> deleted', 'warning')
            db.session.commit()
            return redirect(url_for('projects.projects'))

        elif form.validate():
            project.name = form.name.data
            project.description = form.description.data
            db.session.commit()
            flash(f'Project <strong>{project.name}</strong> updated', 'info')
            return redirect(url_for('projects.projects'))

        else:
            return _render_with_form(form)

    else:
        form = ProjectForm(name=project.name, description=project.description, id=project.id)
        return _render_with_form(form)

@bp.route('/<int:project_id>/phase/add', methods=['POST'])
def project_add_phase(project_id):

    project = Project.query.get(project_id)
    phase_type = PhaseTypeEnum(int(request.form.get('type')))
    order = len(project.phases.all()) + 1
    src_dir = request.form.get('src_dir')
    dest_dir = request.form.get('dest_dir')
    reject_dir = request.form.get('reject_dir')

    phase = Phase(project=project, type=phase_type, order=order, src_dir=src_dir, dest_dir=dest_dir, reject_dir=reject_dir)
    db.session.add(phase, )
    db.session.commit()

    return redirect(url_for('projects.project_edit', project_id=project_id))

@bp.route('/<int:project_id>/phase/<int:phase_order>/remove', methods=['POST'])
def project_remove_phase(project_id, phase_order):

    project = Project.query.get(project_id)
    phase = project.phases.filter(Phase.order==phase_order).first()

    db.session.delete(phase)
    db.session.commit()

    return redirect(url_for('projects.project_edit', project_id=project_id))

@bp.route('/<int:project_id>/phase/<int:phase_order>/work', methods=['GET'])
def project_work_phase(project_id, phase_order):

    project = Project.query.get(project_id)
    phase = project.phases.filter(Phase.order==phase_order).first()

    if project.current_phase != phase.order:
        abort(404)

    SRC_DIR = os.path.join(os.environ['IMAGE_STORAGE_ROOT'], phase.src_dir)

    all_files = [f for f in os.listdir(SRC_DIR) if not f.startswith('.')]
    ALLOWED_FILE_EXTENSIONS = ''
    num_remaining = len(all_files)
    try:
        files = random.sample(all_files, MODERATE_SAMPLE_SIZE)
    except ValueError:
        files = all_files

    data = {
        'project': project,
        'phase': phase,
        'num_remaining': num_remaining,
        'files': files,
        'page_title': f'Phase - {phase.order} | {project.name}',
    }

    return render_template('work.html', **data)

@bp.route('/<int:project_id>/phase/<int:phase_order>/image/<path:filename>', methods=['GET'])
def project_phase_get_image(project_id, phase_order, filename):

    project = Project.query.get(project_id)
    phase = project.phases.filter(Phase.order==phase_order).first()

    if project.current_phase != phase.order:
        abort(404)

    SRC_DIR = os.path.join(os.environ['IMAGE_STORAGE_ROOT'], phase.src_dir)

    return send_from_directory(SRC_DIR, filename)

@bp.route('/<int:project_id>/phase/<int:phase_order>/image/<path:filename>/accept', methods=['POST'])
def project_phase_accept_image(project_id, phase_order, filename):

    project = Project.query.get(project_id)
    phase = project.phases.filter(Phase.order==phase_order).first()

    if project.current_phase != phase.order:
        abort(404)

    src = os.path.join(os.environ['IMAGE_STORAGE_ROOT'], phase.src_dir, filename)
    dst = os.path.join(os.environ['IMAGE_STORAGE_ROOT'], phase.dest_dir, filename)

    move(src, dst)
    return ('', 204)

@bp.route('/<int:project_id>/phase/<int:phase_order>/image/<path:filename>/reject', methods=['POST'])
def project_phase_reject_image(project_id, phase_order, filename):

    project = Project.query.get(project_id)
    phase = project.phases.filter(Phase.order==phase_order).first()

    if project.current_phase != phase.order:
        abort(404)

    src = os.path.join(os.environ['IMAGE_STORAGE_ROOT'], phase.src_dir, filename)
    dst = os.path.join(os.environ['IMAGE_STORAGE_ROOT'], phase.reject_dir, filename)

    move(src, dst)
    return ('', 204)

sila/templates/base.html
<!DOCTYPE html>

<html>
  <head>
    <title>{{ page_title}} | SILA</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/paper-dashboard.min.css') }}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
  </head>

  <body>
    {% block body %}{% endblock %}
    {% block body_script %}{% endblock %}
  </body>
</html>

sila/templates/index.html
{% extends 'base.html' %}

{% block body%}
<div class='wrapper'>
  {% include 'components/sidebar.html' %}

  <div class='main-panel'>
    <div class='content'>
      <div class='-container'>
        <div class='row'>
          <div class='col-md-12'>
            <h2 class='mt-5 mb-5'>Select a task stream</h2>

            <div class='card-group'>

              <div class='card'>
                <div class='card-body'>
                  <h5 class='card-title'>Image Moderation</h5>
                  <h6 class='card-subtitle mb-2 text-muted'>Approve or reject images</h6>
                  <p class='card-text'>Look at random images from a pool of raw images. Approve images that meet the quality standards and reject the ones that do not.</p>
                  <a href='{{ url_for("index") }}' class='btn btn-primary'>Start</a>
                </div>
              </div>

              <div class='card'>
                <div class='card-body'>
                  <h5 class='card-title'>Image Slicing</h5>
                  <h6 class='card-subtitle mb-2 text-muted'>Crop useful bits</h6>
                  <p class='card-text'>Not everything in an image is useful. In this task you shall crop out useful parts from an image.</p>
                  <a href='{{ url_for("index") }}' class='btn btn-primary'>Start</a>
                </div>
              </div>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>


</div>


{% endblock %}

sila/templates/project-form.html
{% extends 'base.html' %}
{% from "components/_formhelpers.html" import render_field %}

{% block title%}{{ page_title }} | SILA{% endblock %}

{% block body%}
<div class='wrapper'>
  {% include 'components/sidebar.html' %}

  <div class='main-panel'>
    <div class='content'>
      <div class='row'>
        <div class='col-md-12'>
          <h2 class='mb-5'>{{ page_title }}</h2>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-12'>
          <div class='card'>
            <div class='card-body'>
              <form method='post'>
                {% for field in form %}
                  {{ render_field(field) }}
                {% endfor %}
                <input type='submit' value='Save' class='btn btn-info btn-fill btn-wd' >
                {% if form.id.data %}
                <input type='submit' value='Delete' name='delete' class='btn btn-danger btn-fill btn-wd pull-right' >
                {% endif %}
              </form>
            </div>
          </div>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-12'>
          <div class='card'>
            <div class='card-body'>
              <h4 class="card-title">Phases</h4>
              <div calss='table-responsive'>
                <table class='table'>
                  <thead class=" text-primary">
                    <tr>
                      <th>Order</th>
                      <th>Type</th>
                      <th>Source directory<a href='#image-storage-root'>*</a></th>
                      <th>Destination directory<a href='#image-storage-root'>*</a></th>
                      <th>Reject directory<a href='#image-storage-root'>*</a></th>
                      <th class="text-right"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for phase in project.phases %}
                    <form
                      method='post'
                      action='{{ url_for("projects.project_remove_phase", project_id=project.id, phase_order=phase.order) }}'
                      onsubmit='return confirm("Do you really want to remove this phase from the project?");'
                    >
                      <tr>
                        <td>{{ phase.order }}</td>
                        <td>{{ phase.type.to_name() }}</td>
                        <td><i class='far fa-folder'></i> {{ phase.src_dir }}</td>
                        <td><i class='far fa-folder'></i> {{ phase.dest_dir }}</td>
                        <td><i class='far fa-folder'></i> {{ phase.reject_dir }}</td>
                        <td>
                          <button class='pull-right btn btn-danger btn-sm btn-delete-phase' data-project-id='{{ project_id }}' data-phase-order='{{ phase.order }}'><i class='fa fa-times'></i></button>
                        </td>
                      </tr>
                    </form>
                    {% endfor %}
                  </tbody>
                </table>
                <span id='image-storage-root'><span>*</span> Relative to IMAGE_STORAGE_ROOT.</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-12'>
          <div class='card'>
            <div class='card-body'>
              <h6 class="card-title">New phase</h6>
              <form method='post' action='{{ url_for("projects.project_add_phase", project_id=project.id) }}'>
                {% for field in new_phase_form %}
                  {{ render_field(field) }}
                {% endfor %}
                <input type='submit' value='Add' class='btn btn-info btn-fill btn-wd' >
              </form>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
{% endblock %}

sila/templates/projects.html
{% extends 'base.html' %}

{% block title%}{{ page_title }} | SILA{% endblock %}

{% block body%}
<div class='wrapper'>
  {% include 'components/sidebar.html' %}

  <div class='main-panel'>
    <div class='content'>

      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class='alert alert-{{category}}'>
              <span>{{ message|safe }}</span>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      <div class='row'>
        <div class='col-md-12'>
          <h2 class='mb-5'>{{ page_title }} <a href='{{ url_for("projects.project_new") }}' class='btn btn-primary btn-sm'><i class='nc-icon nc-simple-add'></i></a></h2>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-12'>
          <div class='card'>
            <div class='card-header'>
              <h4 class='card-title'>Active</h4>
            </div>
            <div class='card-body'>
              <div class="table-responsive">
                <table class="table">
                  <thead class=" text-primary">
                    <tr>
                      <th>Name & Description</th>
                      <th>Phases</th>
                      <th class="text-right">Progress</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for project in active_projects %}
                    <tr>
                      <td>
                        <a href='{{ url_for("projects.project_edit", project_id=project.id) }}' ><h6>{{ project.name }}</h6></a>
                        <p>{{ project.description }}</p>
                      </td>
                      <td>
                        {% for phase in project.phases %}
                          {{ phase.order }}. {{ phase.type.to_name() }}
                          {% if project.current_phase == phase.order %}
                          <a class='btn btn-primary btn-sm' href='{{ url_for("projects.project_work_phase", project_id=project.id, phase_order=phase.order) }}'>Launch</a>
                          {% endif %}
                          <br>
                        {% endfor %}
                      </td>
                      <td class="text-right">n/a</td>
                    </tr>
                    {% endfor %}
                  </table>
                </div>
            </div>
          </div>
        </div>
      </div>

      <div class='row'>
        <div class='col-md-6'>
          <div class='card'>
            <div class='card-header'>
              <h4 class='card-title'>Draft</h4>
            </div>
            <div class='card-body'>
              <div class="table-responsive">
                <table class="table">
                  <thead class=" text-primary">
                    <tr>
                      <th>Name & Description</th>
                      <th>Phases</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for project in draft_projects %}
                    <tr>
                      <td>
                        <h6>{{ project.name }}</h6>
                        <p>{{ project.description }}</p>
                      </td>
                      <td>{{ project.name }}</td>
                    </tr>
                    {% endfor %}
                  </table>
                </div>
            </div>
          </div>
        </div>

        <div class='col-md-6'>
          <div class='card'>
            <div class='card-header'>
              <h4 class='card-title'>Completed</h4>
            </div>
            <div class='card-body'>
              <div class="table-responsive">
                <table class="table">
                  <thead class=" text-primary">
                    <tr>
                      <th>Name & Description</th>
                      <th>Phases</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for project in completed_projects %}
                    <tr>
                      <td>
                        <h6>{{ project.name }}</h6>
                        <p>{{ project.description }}</p>
                      </td>
                      <td>{{ project.name }}</td>
                    </tr>
                    {% endfor %}
                  </table>
                </div>
            </div>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>
{% endblock %}

sila/templates/wip.html
{% extends 'base.html' %}

{% block body%}
<div class='wrapper'>
  {% include 'components/sidebar.html' %}

  <div class='main-panel'>
    <div class='content'>
      <div class='-container'>
        <div class='row'>
          <div class='col-md-12'>
            <h1>This page is under construction.</h1>

          </div>
        </div>
      </div>
    </div>
  </div>


</div>


{% endblock %}

sila/templates/work.html
{% extends 'base.html' %}

{% block title %}kaj{% endblock %}

{% block body%}
<div class='wrapper'>
  {% include 'components/sidebar.html' %}

  <div class='main-panel'>
    <div class='content'>
      <div class='-container'>
        <div class='row'>
          <div class='col-md-12'>
            <h2 class='mt-5 mb-5'>{{ project.name }} - Phase - {{ phase.order }}: {{ phase.type.to_name() }}</h2>

            <table class='table'>
              <tr>
                <td>Source directory</td>
                <td>{{ phase.src_dir }}</td>
              </tr>
              <tr>
                <td>Destination directory</td>
                <td>{{ phase.dest_dir }}</td>
              </tr>
              <tr>
                <td>Reject directory</td>
                <td>{{ phase.reject_dir }}</td>
              </tr>
              <tr>
                <td>Remaining images</td>
                <td>{{ num_remaining }}</td>
              </tr>
            </table>

            {% for file in files %}
            <div class='card moderate-item-container'>
              <div class='card-body'>
                <div class='moderate-item-container d-flex flex-row' data-filename="{{ file }}">
                  <div class="toolbox d-flex flex-column justify-content-around mr-3">
                    <button class="btn-reject" data-filename="{{ file }}"><i class="fas fa-times"></i></a></button>
                    <button class="btn-accept" data-filename="{{ file }}"><i class="fas fa-check"></i></a></button>
                  </div>
                  <a href="{{ url_for('projects.project_phase_get_image', project_id=project.id, phase_order=phase.order, filename=file) }}" target="_blank">
                    <img src="{{ url_for('projects.project_phase_get_image', project_id=project.id, phase_order=phase.order, filename=file) }}" class="moderate-item img-fluid" />
                  </a>
                </div>
              </div>
            </div>
            {% endfor %}

            <div class='mt-5'>
              <button id="btn-save" class="btn btn-lg btn-primary">Save</button>
              <a id="btn-reload" class="btn btn-lg btn-primary" href="">Reload</a>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}

{% block body_script %}
<script>

  $(document).ready(() => {
    $("button.btn-reject").click((event) => {
      const target = $(event.target).closest("button.btn-reject")[0];
      const itemContainer = $(target).closest(".moderate-item-container");
      $(itemContainer).removeClass('accepted');
      $(itemContainer).addClass('rejected');
    })

    $("button.btn-accept").click((event) => {
      const target = $(event.target).closest("button.btn-accept")[0];

      const itemContainer = $(target).closest(".moderate-item-container");
      $(itemContainer).removeClass('rejected');
      $(itemContainer).addClass('accepted');
    })

    $("#btn-save").click(() => {
      const acceptedItems = $(".moderate-item-container.accepted")
        .map(function() { return $(this).data("filename") })
        .toArray();

      const rejectedItems = $(".moderate-item-container.rejected")
        .map(function() { return $(this).data("filename") })
        .toArray();

      console.log(acceptedItems)
      console.log(rejectedItems)

      acceptedItems.forEach((item) => {
        const url = "{{ url_for('projects.project_phase_accept_image', project_id=project.id, phase_order=phase.order, filename='__filename__') }}".replace("__filename__", item);
        const itemContainer = $(`.moderate-item-container[data-filename='${item}']`);
        console.log(url)
        saveVerdict(url, itemContainer);
      })

      rejectedItems.forEach((item) => {
        const url = "{{ url_for('projects.project_phase_reject_image', project_id=project.id, phase_order=phase.order, filename='__filename__') }}".replace("__filename__", item);
        const itemContainer = $(`.moderate-item-container[data-filename='${item}']`);
        saveVerdict(url, itemContainer);
      })
    })
  })

  function saveVerdict(url, itemContainer) {
    fetch(url, {
      method: 'POST',
      cache: 'no-cache',
    }).then(response => {
      if (response.ok) {
        $(itemContainer).remove();
        const numRemainingItems = $(".moderate-item-container").length;
        if (0 === numRemainingItems) {
          window.location.reload();
        }
      } else {
        console.error(response);
      }
    })
  }

</script>
{% endblock %}